language: python
python:
  - "3.5"

sudo: false

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  - python -m pytest --cov=jusdat

after_success:
  - coveralls